# syntax=docker/dockerfile:1

FROM python:3.9-slim-buster

ARG API_PASS
ENV API_PASS=${API_PASS}

WORKDIR /serv

RUN apt-get -y update &&\
    apt-get -y install build-essential &&\
    apt-get -y install libpq-dev &&\
    pip install --upgrade pip

COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt

COPY . .

CMD ["python3", "app.py"]